<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.31">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Evelin Langebeck Cuéllar &amp; Nicolás Giraldo Hernández">
<meta name="keywords" content="community resilience, technological risk, ARC-D tool, disaster risk management, multi-temporal resilience, risk perception">

<title>4. Evaluación multitemporal de la resiliencia comunitaria ante eventos tecnológicos en la Comuna 10 del municipio de Dosquebradas – Investigaciones en Gestión del Riesgo de Desastres para Colombia</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Capitulo5.html" rel="next">
<link href="./Capitulo3.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-e1a5c8363afafaef2c763b6775fbf3ca.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-485d01fc63b59abcd3ee1bf1e8e2748d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Sin resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<style>

      .quarto-title-block .quarto-title-banner h1,
      .quarto-title-block .quarto-title-banner h2,
      .quarto-title-block .quarto-title-banner h3,
      .quarto-title-block .quarto-title-banner h4,
      .quarto-title-block .quarto-title-banner h5,
      .quarto-title-block .quarto-title-banner h6
      {
        color: white;
      }

      .quarto-title-block .quarto-title-banner {
        color: white;
background-image: url(bannerc1.png);
background-size: cover;
      }
</style>
<script>
// Make "Figura X:" bold in captions
document.addEventListener('DOMContentLoaded', function() {
  // Find all figure captions
  const captions = document.querySelectorAll('figcaption.quarto-float-caption');

  captions.forEach(function(caption) {
    // Get the text content
    let text = caption.innerHTML;

    // Replace "Figura X:" with bold version (supports Figura 1, Figura 2, etc.)
    text = text.replace(/^(Figura\s+\d+:)/i, '<strong>$1</strong>');

    // Also handle "Tabla X:" for tables
    text = text.replace(/^(Tabla\s+\d+:)/i, '<strong>$1</strong>');

    caption.innerHTML = text;
  });
});
</script>


<link rel="stylesheet" href="custom.css">
<link rel="stylesheet" href="pdf-styles.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Capitulo1.html">Capítulos</a></li><li class="breadcrumb-item"><a href="./Capitulo4.html"><span class="chapter-title">4. Evaluación multitemporal de la resiliencia comunitaria ante eventos tecnológicos en la Comuna 10 del municipio de Dosquebradas</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Capitulo1.html">Capítulos</a></li><li class="breadcrumb-item"><a href="./Capitulo4.html"><span class="chapter-title">4. Evaluación multitemporal de la resiliencia comunitaria ante eventos tecnológicos en la Comuna 10 del municipio de Dosquebradas</span></a></li></ol></nav>
      <h1 class="title"><span class="chapter-title">4. Evaluación multitemporal de la resiliencia comunitaria ante eventos tecnológicos en la Comuna 10 del municipio de Dosquebradas</span></h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Autor/a</div>
      <div class="quarto-title-meta-contents">
               <p>Evelin Langebeck Cuéllar &amp; Nicolás Giraldo Hernández </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Fecha de publicación</div>
      <div class="quarto-title-meta-contents">
        <p class="date">31 de diciembre de 2024</p>
      </div>
    </div>
    
      
    </div>
    

  <div>
    <div class="keywords">
      <div class="block-title">Palabras clave</div>
      <p>community resilience, technological risk, ARC-D tool, disaster risk management, multi-temporal resilience, risk perception</p>
    </div>
  </div>
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Investigaciones en Gestión del Riesgo de Desastres para Colombia</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Inicio</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Capítulos</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Capitulo1.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1. Entre el conocimiento y la acción: estrategias para la gestión del riesgo de desastres y la adaptación climática en el Valle de Aburrá</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Capitulo2.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">2. Enfoque etnodiferencial y riesgo de desastre en Colombia: líneas de fuga para una digna vida</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Capitulo3.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">3. Gestión del Riesgo de Desastres Comunitario a través de Cartografía Participativa y Tecnologías Abiertas en San José del Prado, Colombia</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Capitulo4.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">4. Evaluación multitemporal de la resiliencia comunitaria ante eventos tecnológicos en la Comuna 10 del municipio de Dosquebradas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Capitulo5.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5. Avances y desafíos del manejo de desastres y gestión del riesgo volcánico con animales de producción</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Referencias</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./glosario.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Glosario e Índice Temático</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./capitulo-plantilla.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1. Terremotos de La Palma: Análisis sísmico de la actividad volcánica</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#resumen" id="toc-resumen" class="nav-link active" data-scroll-target="#resumen">Resumen</a></li>
  <li><a href="#multi-temporal-evaluation-of-community-resilience-to-disasters-due-to-technological-risk-in-commune-10-of-the-municipality-of-dosquebradas" id="toc-multi-temporal-evaluation-of-community-resilience-to-disasters-due-to-technological-risk-in-commune-10-of-the-municipality-of-dosquebradas" class="nav-link" data-scroll-target="#multi-temporal-evaluation-of-community-resilience-to-disasters-due-to-technological-risk-in-commune-10-of-the-municipality-of-dosquebradas">Multi-temporal Evaluation of Community Resilience to Disasters Due to Technological Risk in Commune 10 of the Municipality of Dosquebradas</a></li>
  <li><a href="#introducción" id="toc-introducción" class="nav-link" data-scroll-target="#introducción">1. INTRODUCCIÓN</a></li>
  <li><a href="#metodología" id="toc-metodología" class="nav-link" data-scroll-target="#metodología">2. METODOLOGÍA</a>
  <ul class="collapse">
  <li><a href="#municipio-de-dosquebradas-y-contexto-de-la-comuna-10" id="toc-municipio-de-dosquebradas-y-contexto-de-la-comuna-10" class="nav-link" data-scroll-target="#municipio-de-dosquebradas-y-contexto-de-la-comuna-10">2.1. Municipio de Dosquebradas y contexto de la Comuna 10</a></li>
  <li><a href="#herramienta-arc-d-para-evaluación-de-resiliencia-comunitaria" id="toc-herramienta-arc-d-para-evaluación-de-resiliencia-comunitaria" class="nav-link" data-scroll-target="#herramienta-arc-d-para-evaluación-de-resiliencia-comunitaria">2.2. Herramienta ARC-D para evaluación de resiliencia comunitaria</a>
  <ul class="collapse">
  <li><a href="#componentes-evaluativos-del-arc-d" id="toc-componentes-evaluativos-del-arc-d" class="nav-link" data-scroll-target="#componentes-evaluativos-del-arc-d">2.3. Componentes evaluativos del ARC-D</a></li>
  </ul></li>
  <li><a href="#recolección-y-procesamiento-de-datos-de-percepción-del-riesgo-comunitario" id="toc-recolección-y-procesamiento-de-datos-de-percepción-del-riesgo-comunitario" class="nav-link" data-scroll-target="#recolección-y-procesamiento-de-datos-de-percepción-del-riesgo-comunitario">2.4. Recolección y procesamiento de datos de percepción del riesgo comunitario</a>
  <ul class="collapse">
  <li><a href="#reconocimiento-de-la-comuna-10-y-sus-líderes" id="toc-reconocimiento-de-la-comuna-10-y-sus-líderes" class="nav-link" data-scroll-target="#reconocimiento-de-la-comuna-10-y-sus-líderes">2.4.1 Reconocimiento de la Comuna 10 y sus líderes</a></li>
  <li><a href="#aplicación-de-la-herramienta-arc-d-en-el-grupo-focal" id="toc-aplicación-de-la-herramienta-arc-d-en-el-grupo-focal" class="nav-link" data-scroll-target="#aplicación-de-la-herramienta-arc-d-en-el-grupo-focal">2.4.2 Aplicación de la herramienta ARC-D en el grupo focal</a></li>
  <li><a href="#análisis-de-datos" id="toc-análisis-de-datos" class="nav-link" data-scroll-target="#análisis-de-datos">2.4.3 Análisis de datos</a></li>
  </ul></li>
  <li><a href="#caracterización-del-riesgo-tecnológico-y-condiciones-de-la-comuna-10" id="toc-caracterización-del-riesgo-tecnológico-y-condiciones-de-la-comuna-10" class="nav-link" data-scroll-target="#caracterización-del-riesgo-tecnológico-y-condiciones-de-la-comuna-10">2.5. Caracterización del riesgo tecnológico y condiciones de la Comuna 10</a></li>
  </ul></li>
  <li><a href="#resultados" id="toc-resultados" class="nav-link" data-scroll-target="#resultados">3. RESULTADOS</a>
  <ul class="collapse">
  <li><a href="#evaluación-de-los-componentes-de-resiliencia-comunitaria-ante-desastres" id="toc-evaluación-de-los-componentes-de-resiliencia-comunitaria-ante-desastres" class="nav-link" data-scroll-target="#evaluación-de-los-componentes-de-resiliencia-comunitaria-ante-desastres">3.1 Evaluación de los componentes de resiliencia comunitaria ante desastres</a>
  <ul class="collapse">
  <li><a href="#evaluación-de-resiliencia-comunitaria---año-2011" id="toc-evaluación-de-resiliencia-comunitaria---año-2011" class="nav-link" data-scroll-target="#evaluación-de-resiliencia-comunitaria---año-2011">3.1.1 Evaluación de resiliencia comunitaria - Año 2011</a></li>
  <li><a href="#evaluación-de-resiliencia-comunitaria---año-2021" id="toc-evaluación-de-resiliencia-comunitaria---año-2021" class="nav-link" data-scroll-target="#evaluación-de-resiliencia-comunitaria---año-2021">3.1.2 Evaluación de resiliencia comunitaria - Año 2021</a></li>
  </ul></li>
  <li><a href="#análisis-comparativo-multitemporal" id="toc-análisis-comparativo-multitemporal" class="nav-link" data-scroll-target="#análisis-comparativo-multitemporal">3.2 Análisis comparativo multitemporal</a></li>
  </ul></li>
  <li><a href="#discusión" id="toc-discusión" class="nav-link" data-scroll-target="#discusión">4. DISCUSIÓN</a></li>
  <li><a href="#conclusiones" id="toc-conclusiones" class="nav-link" data-scroll-target="#conclusiones">5. CONCLUSIONES</a></li>
  <li><a href="#conflicto-de-intereses" id="toc-conflicto-de-intereses" class="nav-link" data-scroll-target="#conflicto-de-intereses">CONFLICTO DE INTERESES</a></li>
  <li><a href="#uso-de-herramientas-de-inteligencia-artificial" id="toc-uso-de-herramientas-de-inteligencia-artificial" class="nav-link" data-scroll-target="#uso-de-herramientas-de-inteligencia-artificial">USO DE HERRAMIENTAS DE INTELIGENCIA ARTIFICIAL</a></li>
  <li><a href="#agradecimientos" id="toc-agradecimientos" class="nav-link" data-scroll-target="#agradecimientos">AGRADECIMIENTOS</a></li>
  <li><a href="#identificación-de-autores" id="toc-identificación-de-autores" class="nav-link" data-scroll-target="#identificación-de-autores">IDENTIFICACIÓN DE AUTORES</a></li>
  <li><a href="#declaración-de-autoría-credit" id="toc-declaración-de-autoría-credit" class="nav-link" data-scroll-target="#declaración-de-autoría-credit">DECLARACIÓN DE AUTORÍA CRediT</a></li>
  <li><a href="#bibliografía" id="toc-bibliografía" class="nav-link" data-scroll-target="#bibliografía">BIBLIOGRAFÍA</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="resumen" class="level1" style="padding-top: 0.5rem; padding-bottom: 0.5rem;">
<h1>Resumen</h1>
<p>La resiliencia comunitaria es la capacidad de una población a enfrentar, responder y adaptarse a emergencias y desastres manteniendo su estructura básica, función e identidad. Sin embargo, la resiliencia comunitaria ante eventos tecnológicos ha sido escasamente estudiada en Colombia. Aquí se mide y evalúa la resiliencia comunitaria ante desastres empleando la aplicación de la herramienta ARC-D en una población del municipio de Dosquebradas (barrio Villa Carola) dónde en 2011 ocurrió un proceso de remoción en masa que desencadenó un derrame de hidrocarburos generando la pérdida de 33 vidas debido a una explosión y desbordando las capacidades de respuesta del municipio. Seguimos una metodología con enfoque cualitativo para la interacción comunidad-territorio y una con enfoque cuantitativo para el procesamiento de datos. Para la discusión comunitaria se empleó un instrumento tipo encuesta medida por grupo focal con facilitador, en la que se evaluaron cuatro áreas temáticas. La aplicación de la herramienta tuvo un diagnóstico de resiliencia previo y una prueba piloto de ajuste al grupo focal. Encontramos un nivel bajo de resiliencia para el año (2011) con un mayor énfasis en la baja comprensión del riesgo, contrario al componente más alto que corresponde a cohesión social en el territorio. El año (2021) registró un nivel de mediana resiliencia con mejores resultados en el fortalecimiento de la gobernanza para gestionar el riesgo de desastres, reflejado en su componente destacado, que fue la participación de las mujeres. Concluimos que en la Comuna 10 de Dosquebradas mejoró sus capacidades de resiliencia comunitaria ante desastres por riesgo tecnológico de 30,08% a 60,18%, destacando el aumento de la participación comunitaria, la organización social y la apropiación de la cultura de la prevención del riesgo.</p>
</section>
<div id="abstract" style="padding-top: 0.5rem; padding-bottom: 0.5rem;">
<section id="multi-temporal-evaluation-of-community-resilience-to-disasters-due-to-technological-risk-in-commune-10-of-the-municipality-of-dosquebradas" class="level1">
<h1>Multi-temporal Evaluation of Community Resilience to Disasters Due to Technological Risk in Commune 10 of the Municipality of Dosquebradas</h1>
<p><strong>Abstract</strong>. Community resilience is the capacity of a population to face, respond to, and adapt to emergencies and disasters while maintaining its basic structure, function, and identity. However, community resilience in the face of technological events has been scarcely studied in Colombia. This study measures and evaluates community resilience to disasters by applying the ARC-D tool in a population in the municipality of Dosquebradas (Villa Carola neighborhood), where in 2011, a mass removal event triggered a hydrocarbon spill, causing the loss of 33 lives due to an explosion and overwhelming the municipality’s response capacity. A qualitative methodology was followed for the community-territory interaction, and a quantitative approach was used for data processing. For the community discussion, a survey-type instrument was used, measured through a focus group with a facilitator, in which four thematic areas were assessed. The application of the tool included a preliminary resilience diagnosis and a pilot adjustment test for the focus group. We found a low resilience level in 2011, primarily due to a low understanding of risk, which contrasted with the highest component, social cohesion in the territory. The year 2021 recorded a medium resilience level, with improved results in strengthening governance to manage disaster risk, reflected in the highlighted component: women’s participation. We concluded that the resilience capacity of Community 10 in Dosquebradas improved its community resilience to technological disaster risks from 30.08% to 60.18%, with notable increases in community participation, social organization, and the appropriation of risk prevention culture.</p>
</section>
</div>
<section id="introducción" class="level1">
<h1>1. INTRODUCCIÓN</h1>
<p>La resiliencia comunitaria es la capacidad de las comunidades y hogares que viven dentro de sistemas complejos para anticiparse y adaptarse a los riesgos, para absorber, responder y recuperarse de las amenazas y estresores de una manera oportuna y efectiva sin comprometer sus posibilidades a largo plazo, mejorando finalmente su bienestar <span class="citation" data-cites="cruzroja2006">[<a href="Capitulo1.html#ref-cruzroja2006" role="doc-biblioref">1</a>]</span>. Este definición sigue la del grupo de trabajo intergubernamental de expertos de composición abierta sobre los indicadores mundiales para las metas mundiales del Marco de Sendai que define la resiliencia como “la capacidad que tiene un sistema, una comunidad o una sociedad expuestos a una amenaza para resistir, absorber, adaptarse, transformarse y recuperarse de sus efectos de manera oportuna y eficiente, en particular mediante la preservación y la restauración de sus estructuras y funciones básicas por conducto de la gestión de riesgos” <span class="citation" data-cites="onu2016">[<a href="Capitulo1.html#ref-onu2016" role="doc-biblioref">2</a>]</span>. Otras aproximaciones definen la resiliencia comunitaria como la capacidad de los sistemas para hacer frente y adaptarse a eventos extremos, sin perder su estructura básica, y hace énfasis en que la cultura de la resiliencia permite reducir pérdidas humanas, socioeconómicas y ambientales <span class="citation" data-cites="ciccotti2020">[<a href="Capitulo1.html#ref-ciccotti2020" role="doc-biblioref">3</a>]</span></p>
<p>La resiliencia comunitaria tiene dos componentes. Primero, la capacidad de adaptación, que se define como las condiciones que permiten a las personas y/o comunidades anticipar y responder al cambio, minimizar las consecuencias, recuperarse y aprovechar las nuevas oportunidades <span class="citation" data-cites="unisdr2009">[<a href="Capitulo1.html#ref-unisdr2009" role="doc-biblioref">4</a>]</span>. Segundo, la percepción del riesgo, en el cual las comunidades perciben el riesgo basado en procesos cognitivos influidos por diversos factores, tales como las características y la gravedad del riesgo, experiencias previas, la cantidad y calidad de la información disponible, así como los valores individuales y sociales y el conocimiento sobre el fenómeno que genera el riesgo <span class="citation" data-cites="mccaul2016">[<a href="Capitulo1.html#ref-mccaul2016" role="doc-biblioref">5</a>]</span>.</p>
<p>La importancia de considerar la percepción del riesgo de desastres como una necesidad reciente, especialmente en el contexto del cambio climático y el incremento de desastres, ha sido abordado en análisis de percepción del riesgo, a partir de métodos psicosociales sustentados en la subjetividad de los seres humanos ante los escenarios de riesgo presentes en sus entornos <span class="citation" data-cites="sandoval2022">[<a href="Capitulo1.html#ref-sandoval2022" role="doc-biblioref">6</a>]</span>. Sin embargo, los enfoques se han direccionado a eventos de tipo natural y socio-natural dejando a un lado los escenarios de riesgo antrópico-tecnológicos. Los riesgos tecnológicos en Sudamérica han sido poco explorados a partir de ejercicios de percepción del riesgo que permitan establecer niveles de resiliencia comunitaria ante este tipo de eventos.</p>
<p>Los autores Sandoval, Navarrete, &amp; Cuadra <span class="citation" data-cites="sandoval2022">[<a href="Capitulo1.html#ref-sandoval2022" role="doc-biblioref">6</a>]</span> resaltan que la resiliencia comunitaria se ha estudiado en Latinoamérica principalmente en países como Chile, seguido de Puerto Rico y Brasil. Los principales riesgos estudiados son terremotos (12), inundaciones (11) y tsunamis (7), y los escasamente estudiados son sequías, erupciones volcánicas y eventos extremos vinculados al cambio climático <span class="citation" data-cites="sandoval2022">[<a href="Capitulo1.html#ref-sandoval2022" role="doc-biblioref">6</a>]</span>. Los autores afirman que en Latinoamérica una de las principales barreras para el desarrollo o despliegue de la resiliencia comunitaria, son las condiciones de vulnerabilidad en las dimensiones políticas, sociales, económicas y ambientales. Frente a este panorama, en Colombia la resiliencia comunitaria ha sido escasamente estudiada y los trabajos realizados se han enfocado en análisis comparativos a partir de índices compuestos de resiliencia para dimensiones ecosistémicas <span class="citation" data-cites="sandoval2022">[<a href="Capitulo1.html#ref-sandoval2022" role="doc-biblioref">6</a>]</span>.</p>
<p>Aquí presentamos la evaluación de la resiliencia comunitaria multitemporal entre los años 2011 y 2021 el municipio de Dosquebradas en el barrio Villa Carola, dónde en 2011 ocurrió un evento de origen natural que desencadenó un accidente tecnológico o Natech, debido a un proceso de remoción en masa que causó el derrame de hidrocarburos ocasionando 33 muertes debido a una explosión por el hidrocarburo derramado en un punto caliente y desbordando las capacidades de respuesta municipales (Ver <a href="#box1">Caja 1</a>).</p>
<p>Actualmente, la Comuna 10 donde se ubica el barrio Villa Carola, presenta múltiples amenazas socio-naturales por deslizamientos y amenazas tecnológicas por actividades industriales, transporte de hidrocarburos a partir de infraestructura como poliductos y gasoductos, transporte de sustancias peligrosas a partir de vehículos cisterna, aglomeración de público, entre otras.</p>
<div id="box1" class="callout callout-style-simple callout-important no-icon" style="background-color: #e3f0fbff; border-left: 4px solid #d4e8f9ff;">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<h2 style="font-size: 1rem; margin-top: 0; margin-bottom: 0;" class="anchored" data-anchor-id="introducción">
Caja 1. Desastre tecnológico en la Comuna 10 de Dosquebradas en el año 2011
</h2>
<p>El 23 de diciembre de 2011 ocurrió en la Comuna 10 de Dosquebradas una de las tragedias más graves asociadas a riesgo tecnológico en Colombia. Una fuga de combustible en el poliducto Puerto Salgar–Cartago descendió por la quebrada Aguazul y al entrar en contacto con una fuente de calor, desencadenó una serie de explosiones. El evento afectó principalmente a los barrios Villa Carola, La Divisa, La Romelia en la Comuna 10 del municipio, dejando 33 personas fallecidas, 110 heridas, más de cien viviendas afectadas y 38 destruidas, además de pérdidas en establecimientos comerciales.</p>
<div id="fig-desastre2011" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-desastre2011-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/capitulo4/desastre-2011-villa-carola.png" class="img-fluid figure-img" width="500">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-desastre2011-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;1: Escena del desastre tecnológico de 2011 en Villa Carola, Dosquebradas.
</figcaption>
</figure>
</div>
<p>Las causas se atribuyeron tanto a factores antrópicos, como la presencia de válvulas ilegales en el poliducto, como a factores naturales, en particular la reptación del terreno producto de la ola invernal de 2011, que generó tensiones y la fractura de la tubería. El desastre también impactó ambientalmente la quebrada Aguazul, contaminada con más de 1,400 galones de gasolina que afectaron su ronda hídrica y la bocatoma que abastecía a cerca de 25,000 personas.</p>
<p>La atención inmediata contó con la participación de la comunidad, organismos de socorro, autoridades locales y nacionales, así como la empresa Ecopetrol. Posteriormente, se desarrollaron procesos de diálogo y reparación, que permitieron una recuperación colectiva menos traumática y consolidaron aprendizajes comunitarios sobre la gestión del riesgo.</p>
</div>
</div>
</div>
</section>
<section id="metodología" class="level1">
<h1>2. METODOLOGÍA</h1>
<section id="municipio-de-dosquebradas-y-contexto-de-la-comuna-10" class="level2">
<h2 class="anchored" data-anchor-id="municipio-de-dosquebradas-y-contexto-de-la-comuna-10">2.1. Municipio de Dosquebradas y contexto de la Comuna 10</h2>
<p>El municipio de Dosquebradas pertenece al departamento de Risaralda en Colombia. Se encuentra en el sector oriental del departamento y se ubica en la parte occidental de la Cordillera Central. Sus límites municipales son al norte y al este con el municipio de Santa Rosa, al sur con la ciudad de Pereira, y al noroeste con el municipio de Marsella. Dosquebradas se compone de su casco urbano con más de trescientos barrios, dos centros poblados y veinticinco veredas. La población es de 217,178 habitantes, distribuidos en 77,387 unidades de vivienda y 64,576 hogares. La proyección poblacional ajustada indica que el 94.6% pertenece a la cabecera municipal, mientras que el 5.4% pertenece a los centros poblados y rurales dispersos.</p>
<p>En la <a href="#fig-mapa-dosquebradas" class="quarto-xref">Figura&nbsp;<span>2</span></a> se visualiza la localización de la Comuna 10 del municipio de Dosquebradas y la distribución espacial del estado de la comuna frente a escenarios de amenaza o riesgo, tanto de tipo tecnológico como socio-natural, identificados en el territorio. Se observan las amenazas tecnológicas, entre ellas las áreas de aglomeración, las rutas de transporte de carga y los sectores de almacenamiento de carga, en el contexto de la dinámica urbana y social de la comuna. Además, zonas con amenaza por movimientos en masa, red hidrográfica y líneas de tensión eléctrica que atraviesan el área también se diferencian en sectores clasificados como de alto riesgo mitigable y alto riesgo no mitigable por fenómenos recurrentes.</p>
<div id="fig-mapa-dosquebradas" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mapa-dosquebradas-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/capitulo4/mapa-dosquebradas-comuna10.jpg" class="img-fluid figure-img" width="600">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mapa-dosquebradas-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;2: Mapa de localización del municipio de Dosquebradas y la Comuna 10.
</figcaption>
</figure>
</div>
</section>
<section id="herramienta-arc-d-para-evaluación-de-resiliencia-comunitaria" class="level2">
<h2 class="anchored" data-anchor-id="herramienta-arc-d-para-evaluación-de-resiliencia-comunitaria">2.2. Herramienta ARC-D para evaluación de resiliencia comunitaria</h2>
<p>Se utilizó la herramienta ARC-D para medir la resiliencia comunitaria ante desastres desarrollada por la organización GOAL (https://www.goalglobal.org/). Esta herramienta tiene un enfoque mixto, con elementos cualitativos y cuantitativos. El enfoque cualitativo hace referencia a la interacción con la comunidad de los territorios, con los cuales se recoge la información desde una perspectiva social y comunitaria, a través de un instrumento tipo encuesta de 30 preguntas (<a href="#fig-arcd-componentes" class="quarto-xref">Figura&nbsp;<span>3</span></a>), las cuales cuentan con instrumentos de verificación. El enfoque cuantitativo se refiere al procesamiento de los datos y permite obtener gráficos de red para la sistematización y presentación de la información de tipo numérico y jerárquico. La herramienta cuenta con dos etapas. Una etapa A que realiza un diagnóstico general de la comunidad y una etapa B, que se enfoca en las preguntas de evaluación en el grupo focal (<a href="#fig-arcd-componentes" class="quarto-xref">Figura&nbsp;<span>3</span></a>).</p>
<div id="caja2" class="callout callout-style-simple callout-important no-icon" style="background-color: #e3f0fbff; border-left: 4px solid #d4e8f9ff;">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<h2 style="font-size: 1rem; margin-top: 0; margin-bottom: 0;" class="anchored">
Caja 2. Etapas de la herramienta ARC-D de GOAL y glosario de términos
</h2>
<div id="fig-arcd-componentes" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-arcd-componentes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/capitulo4/componentes-arcd.png" class="img-fluid figure-img" width="500">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-arcd-componentes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3: Componentes herramienta ARC-D. La herramienta de evaluación de resiliencia comunitaria establecida por GOAL evalúa cuatro áreas temáticas que conforman 30 componentes.
</figcaption>
</figure>
</div>
<p><strong>Categorías de evaluación de la herramienta ARC-D de GOAL:</strong></p>
<div id="tbl-categorias-arcd" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-categorias-arcd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;1: Categorías de evaluación de la herramienta ARC-D.
</figcaption>
<div aria-describedby="tbl-categorias-arcd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 60%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"><strong>%</strong></th>
<th style="text-align: center;"><strong>Nivel</strong></th>
<th style="text-align: center;"><strong>Categoría</strong></th>
<th style="text-align: left;"><strong>Descripción</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0-20</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">Mínima Resiliencia</td>
<td style="text-align: left;">Poca conciencia del problema o poca motivación. Acciones limitadas.</td>
</tr>
<tr class="even">
<td style="text-align: center;">21-40</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">Baja Resiliencia</td>
<td style="text-align: left;">Conciencia del problema con capacidad limitada de actuar.</td>
</tr>
<tr class="odd">
<td style="text-align: center;">41-60</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">Mediana Resiliencia</td>
<td style="text-align: left;">Desarrollo de soluciones con capacidad mejorada de actuar.</td>
</tr>
<tr class="even">
<td style="text-align: center;">61-80</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">Resiliencia</td>
<td style="text-align: left;">Coherencia e integración con intervenciones amplias y estratégicas.</td>
</tr>
<tr class="odd">
<td style="text-align: center;">81-100</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">Alta Resiliencia</td>
<td style="text-align: left;">Cultura de seguridad integrada en políticas y comportamientos.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>Glosario de términos relacionados con la herramienta ARC-D:</strong></p>
<ul>
<li><p><strong>Capacidad:</strong> Es la habilidad de las personas, instituciones y sociedades para llevar a cabo funciones, resolver problemas y fijarse y obtener objetivos. La capacidad puede incluir infraestructura y medios físicos, instituciones, habilidades de adaptación de las sociedades, así como conocimiento humano, habilidades y atributos colectivos.</p></li>
<li><p><strong>Estresores:</strong> Los estresores son tendencias a largo plazo que socavan el potencial de un sistema o proceso y que aumentan la vulnerabilidad de los actores dentro de ella. Estos pueden ser degradación de los recursos naturales, pérdida en la producción agrícola, urbanización, cambios demográficos, cambio climático, inestabilidad política y reducción en los ingresos.</p></li>
<li><p><strong>Gobernanza:</strong> La gobernanza es el proceso de toma de decisiones y la subsecuente implementación de esas decisiones. Es el ejercicio de la autoridad política, económica y administrativa en el manejo de los asuntos de un país en todos los niveles.</p></li>
</ul>
</div>
</div>
</div>
<section id="componentes-evaluativos-del-arc-d" class="level3">
<h3 class="anchored">2.3. Componentes evaluativos del ARC-D</h3>
<p>La herramienta ARC-D estructura la resiliencia comunitaria en cuatro áreas temáticas que responden a los objetivos del marco de Sendai, que permiten analizar de manera ampla las capacidades de una comunidad frente a situaciones de desastre.</p>
<p>La primera área temática corresponde a comprender el riesgo de desastres, la cual busca identificar en qué medida la comunidad reconoce y se apropia del conocimiento sobre sus amenazas, así como de las estrategias de sensibilización y educación. Se agrupa en cuatro componentes: evaluación participativa y evaluación científica del riesgo, la difusión de información y la educación de los niños en reducción de riesgo.</p>
<p>La segunda área temática se orienta a fortalecer la gobernanza para gestionar el riesgo de desastres y reúne siete componentes. En este caso, los componentes que se abordan son los mecanismos de planificación del desarrollo y planificación territorial, la toma de decisiones colectivas, la inclusión de grupos vulnerables y de mujeres, el conocimiento de derechos, así como las alianzas para la reducción de riesgo y los procesos de recuperación.</p>
<p>La tercera área temática corresponde a reducir la vulnerabilidad a desastres para mejorar la resiliencia que contempla doce componentes: la gestión ambiental sostenible, la seguridad y gestión del agua, el acceso y conciencia de la salud, el suministro seguro de alimentos, las prácticas de medios de vida resistentes a amenazas, el acceso a mercado, el acceso a servicios financieros, la protección de ingresos y activos, el acceso a protección social, la cohesión social y prevención de conflictos, la infraestructura crítica y la vivienda.</p>
<p>Finalmente, la cuarta área temática se dedica a mejorar la preparación ante desastres para lograr respuestas efectivas y promover la reconstrucción resiliente después de una emergencia y se conformada por siete componentes que abarcan: la planificación de contingencia y recuperación, los sistemas de alerta temprana, la capacidad de preparación y respuesta, los servicios de salud y educación durante emergencias, la infraestructura en contextos de crisis y el liderazgo comunitario en la respuesta y la recuperación.</p>
<div id="caja3" class="callout callout-style-simple callout-important no-icon" style="background-color: #e3f0fbff; border-left: 4px solid #d4e8f9ff;">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<h2 style="font-size: 1rem; margin-top: 0; margin-bottom: 0;" class="anchored" data-anchor-id="componentes-evaluativos-del-arc-d">
Caja 3. Glosario de términos relacionados con el riesgo tecnológico
</h2>
<ul>
<li><p><strong>Accidente tecnológico:</strong> Eventos generados por el uso y acceso a la tecnología, originados por eventos antrópicos, naturales, socio-naturales y propios de la operación. Comprende fugas, derrames, incendios y explosiones asociados a la liberación súbita de sustancias y/o energías con características de peligrosidad.</p></li>
<li><p><strong>Amenaza tecnológica:</strong> Amenaza relacionada con accidentes tecnológicos o industriales, procedimientos peligrosos, fallos de infraestructura o de ciertas actividades humanas, que pueden causar muerte o lesiones, daños materiales, interrupción de la actividad social y económica o degradación ambiental.</p></li>
<li><p><strong>Riesgo tecnológico:</strong> Daños o pérdidas potenciales que pueden presentarse debido a los eventos generados por el uso y acceso a la tecnología, originados en sucesos antrópicos, naturales, socio-naturales y propios de la operación.</p></li>
</ul>
</div>
</div>
</div>
</section>
</section>
<section id="recolección-y-procesamiento-de-datos-de-percepción-del-riesgo-comunitario" class="level2">
<h2 class="anchored" data-anchor-id="recolección-y-procesamiento-de-datos-de-percepción-del-riesgo-comunitario">2.4. Recolección y procesamiento de datos de percepción del riesgo comunitario</h2>
<section id="reconocimiento-de-la-comuna-10-y-sus-líderes" class="level3">
<h3 class="anchored" data-anchor-id="reconocimiento-de-la-comuna-10-y-sus-líderes">2.4.1 Reconocimiento de la Comuna 10 y sus líderes</h3>
<p>La fase exploratoria consistió en actividades encaminadas a la revisión de información bibliográfica de artículos, publicaciones y metodologías relacionadas con resiliencia comunitaria, riesgo tecnológico, percepción del riesgo e instrumentos de planificación de gestión del riesgo de orden local.</p>
<p>Previo a la aplicación de la herramienta, se realizó el acercamiento al territorio y la comunidad mediante una visita de campo, tres reuniones preliminares virtuales y una reunión presencial con los líderes comunitarios para socializar el objetivo de la aplicación de la herramienta ARC-D. Igualmente, se efectuó una prueba piloto que permitió ajustar la herramienta de manera conceptual y metodológica, generando adaptaciones a los formatos de aplicación y a una mejor contextualización del ejercicio.</p>
<p>El riesgo considerado en la Comuna 10 fue ante eventos tecnológicos, dados los antecedentes de la explosión de Villa Carola en el año 2011 y la presencia de zonas potenciales de riesgo tecnológico en varias zonas de la comuna. Esto, a su vez, permitió establecer el criterio de multitemporalidad en la medición de la resiliencia comunitaria, algo innovador en la aplicación del ARC-D.</p>
</section>
<section id="aplicación-de-la-herramienta-arc-d-en-el-grupo-focal" class="level3">
<h3 class="anchored" data-anchor-id="aplicación-de-la-herramienta-arc-d-en-el-grupo-focal">2.4.2 Aplicación de la herramienta ARC-D en el grupo focal</h3>
<p>Durante octubre de 2021, se llevó a cabo en el barrio Villa Carola del municipio de Dosquebradas la sesión de grupo focal con 14 líderes comunitarios de diferentes barrios de la Comuna 10, en donde se evaluaron los 30 componentes de la herramienta ARC-D.</p>
<p>El desarrollo de la actividad consistió en la evaluación por la comunidad de la percepción de riesgo frente a escenarios de riesgo de tipo tecnológico, entendiendo los antecedentes de emergencias y desastres ocurridos en la Comuna por este tipo de eventos, específicamente el evento del año 2011. Con base en lo anterior, y dado que la comunidad había presenciado el evento de 2011, así como la etapa de rehabilitación y reconstrucción del barrio Villa Carola, se propuso a los asistentes que la evaluación de la aplicación de la herramienta ARC-D se dividiera en dos momentos. El primer momento era la evaluación en retrospectiva de cómo se percibían los componentes evaluados del 2011 hacia atrás, y un segundo momento, en el que se evaluara la percepción actual de riesgo (año 2021) considerando los mismos 30 componentes del ARC-D frente a eventos tecnológicos.</p>
<div id="fig-grupo-focal-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-grupo-focal-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/capitulo4/grupo-focal-arcd.jpg" class="img-fluid figure-img" width="600">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-grupo-focal-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4: Aplicación de la herramienta ARC-D con grupo focal, líderes de la Comuna 10 el 09 de octubre de 2021.
</figcaption>
</figure>
</div>
</section>
<section id="análisis-de-datos" class="level3">
<h3 class="anchored" data-anchor-id="análisis-de-datos">2.4.3 Análisis de datos</h3>
<p>Se analizó la información obtenida en campo y en el grupo focal, la cual consistió en las siguientes actividades. La primera parte consiste en el análisis de las encuestas, el cual se realizó mediante el procesamiento de la información en el software CommCare, donde se registraron los datos y posteriormente se integraron a la plataforma de GOAL. El diligenciamiento de la información permitió obtener el registro de la Comuna 10 en la plataforma Nexus, donde la información fue representada a través de gráficos de red.</p>
<p>Se consideró el análisis de entrevistas previas, y se examinó la información cualitativa aportada por los participantes, lo que permitió contextualizar los resultados de las encuestas y profundizar en las percepciones de la comunidad sobre los diferentes componentes de la resiliencia, útiles en el análisis y comprensión de la comunidad frente a los riesgos tecnológicos presentados en su localidad.</p>
<p>Posteriormente, se realizó el análisis comparativo de resultados de la evaluación, considerando cada componente de la herramienta y estableciendo un contraste temporal entre los años 2011 antes de la explosión y 2021 después de la explosión y de los procesos de recuperación y reconstrucción, con el fin de identificar los cambios, las mejoras y los aspectos que requieren mayor intervención en las capacidades de resiliencia de la comunidad frente a eventos tecnológicos.</p>
</section>
</section>
<section id="caracterización-del-riesgo-tecnológico-y-condiciones-de-la-comuna-10" class="level2">
<h2 class="anchored" data-anchor-id="caracterización-del-riesgo-tecnológico-y-condiciones-de-la-comuna-10">2.5. Caracterización del riesgo tecnológico y condiciones de la Comuna 10</h2>
<p>La caracterización de riesgos tecnológicos en el municipio de Dosquebradas se identifican sectorialmente por comunas. Esta caracterización se basa en la información disponible en los instrumentos de planificación del municipio de Dosquebradas (<a href="#tbl-riesgos-tecnologicos" class="quarto-xref">Tabla&nbsp;<span>2</span></a>).</p>
<div id="tbl-riesgos-tecnologicos" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-riesgos-tecnologicos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;2: Riesgos tecnológicos asociados por comuna para el municipio de Dosquebradas.
</figcaption>
<div aria-describedby="tbl-riesgos-tecnologicos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 73%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"><strong>Comuna o Corregimiento</strong></th>
<th style="text-align: left;"><strong>Riesgo tecnológico asociado</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Comuna 10 (Villa Carola)</td>
<td style="text-align: left;">Estaciones de servicio, sector industrial, circulación de hidrocarburos</td>
</tr>
<tr class="even">
<td style="text-align: center;">Alto del Nudo</td>
<td style="text-align: left;">Tuberías de conducción, sector industrial, comercial y particulares</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Las condiciones comunitarias de la Comuna 10 de Dosquebradas incluyen barrios, organizaciones comunitarias y características económicas (<a href="#fig-caracteristicas-comuna" class="quarto-xref">Figura&nbsp;<span>5</span></a>). La comuna se conforma de 19 barrios incluyendo Villa Carola, La Romelia, La Divisa, Galaxia, Las Acacias, Los Pinos, Los Guamos, y otros sectores de importancia socioeconómica.</p>
<div id="fig-caracteristicas-comuna" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-caracteristicas-comuna-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/capitulo4/caracteristicas-comuna10.png" class="img-fluid figure-img" width="500">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-caracteristicas-comuna-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;5: Características comunitarias de la Comuna 10 de Dosquebradas.
</figcaption>
</figure>
</div>
</section>
</section>
<section id="resultados" class="level1">
<h1>3. RESULTADOS</h1>
<section id="evaluación-de-los-componentes-de-resiliencia-comunitaria-ante-desastres" class="level2">
<h2 class="anchored" data-anchor-id="evaluación-de-los-componentes-de-resiliencia-comunitaria-ante-desastres">3.1 Evaluación de los componentes de resiliencia comunitaria ante desastres</h2>
<p>Los resultados obtenidos mediante la calificación de la comunidad dan cuenta de la multitemporalidad. Se identificó el nivel de resiliencia comunitaria ante desastres en el año 2011, en el cual ocurrió el evento, y en el año 2021, con el fin de hacer un contraste de las condiciones y poder generar recomendaciones. En la <a href="#tbl-resultados-arcd" class="quarto-xref">Tabla&nbsp;<span>3</span></a> se presentan los resultados por componentes y por temporalidad.</p>
<div id="tbl-resultados-arcd" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-resultados-arcd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;3: Calificaciones de los componentes de resiliencia comunitaria ante desastres según ARC-D.
</figcaption>
<div aria-describedby="tbl-resultados-arcd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 40%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"><strong>Áreas Temáticas</strong></th>
<th style="text-align: center;"><strong>Componentes de Resiliencia a Desastres</strong></th>
<th style="text-align: center;"><strong>Calificación 2011</strong></th>
<th style="text-align: center;"><strong>Calificación 2021</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1. Comprender el riesgo de desastres</td>
<td style="text-align: center;">Evaluación comunitaria participativa</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;">Evaluación científica del riesgo</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;">Diseminación de información en RRD</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;">Educación de los niños en RRD</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2. Fortalecer la Gobernanza</td>
<td style="text-align: center;">RRD en planificación del desarrollo</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;">RRD en planificación territorial</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;">Toma comunitaria de decisiones</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;">Inclusión de grupos vulnerables</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;">Participación de las mujeres</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">5</td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;">Conocimiento de derechos e incidencia</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;">Alianzas para la RRD</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="even">
<td style="text-align: center;">3. Reducir la Vulnerabilidad</td>
<td style="text-align: center;">Gestión ambiental sostenible</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;">Seguridad y gestión del agua</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;">Acceso y conciencia de la salud</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;">Suministro seguro de alimentos</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;">Prácticas de medios de vida resistentes</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;">Acceso a mercado</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;">Acceso a servicios financieros</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;">Protección de ingresos y activos</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;">Acceso a protección social</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;">Cohesión social y prevención de conflictos</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;">Infraestructura Crítica</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;">Vivienda</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: center;">4. Mejorar la Preparación</td>
<td style="text-align: center;">Planificación de contingencia y recuperación</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;">Sistema de alerta temprana</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;">Capacidad de preparación, respuesta y recuperación</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;">Servicios de salud durante emergencias</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;">Servicios de educación en emergencias</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;">Infraestructura en emergencias</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;">Liderazgo y voluntariado en respuesta</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>TOTAL</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>50</strong></td>
<td style="text-align: center;"><strong>96</strong></td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>NIVEL DE RESILIENCIA COMUNITARIA</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>30.08% BAJA</strong></td>
<td style="text-align: center;"><strong>60.18% MEDIANA</strong></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<section id="evaluación-de-resiliencia-comunitaria---año-2011" class="level3">
<h3 class="anchored" data-anchor-id="evaluación-de-resiliencia-comunitaria---año-2011">3.1.1 Evaluación de resiliencia comunitaria - Año 2011</h3>
<p>En los resultados de medición de resiliencia comunitaria se observa que para el año 2011, se obtuvo una calificación del 30.08% categorizada como baja resiliencia según los criterios de la <a href="#tbl-categorias-arcd" class="quarto-xref">Tabla&nbsp;<span>1</span></a>. La comunidad calificó 14 componentes con un nivel de 1, valoración que corresponde a la mínima resiliencia, que se describe como poca conciencia del problema o poca motivación para abordarlo, lo que limita la respuesta durante la crisis.</p>
<p>Lo anterior concuerda con lo expresado en el grupo focal, por parte de los líderes, quienes aseguran que, en ese año, no se contaba con un escenario fortalecido de gobernanza para gestionar el riesgo de desastres. Asimismo, el área temática de la reducción de la vulnerabilidad evidenció la falta de preparación del municipio y su comunidad para abordar el evento de riesgo tecnológico que cobró 33 vidas en la Comuna 10. Frente a la preparación del desastre para una respuesta efectiva, se considera una mínima planificación de contingencia y recuperación durante el año 2011 en la comuna, lo que conllevó a agudizar el evento (<a href="#fig-resultados-2011" class="quarto-xref">Figura&nbsp;<span>6</span></a>).</p>
<p>Por su parte, la medición arrojó 15 componentes con un nivel 2, los cuales se describen como de baja resiliencia, en donde se tiene conciencia del problema, se cuenta con capacidad para actuar, pero de manera limitada, con intervenciones fragmentadas y a corto plazo. El tema del liderazgo y voluntariado, arrojó una puntuación con un valor de 3, que corresponde a mediana resiliencia, en dónde se caracteriza por el desarrollo e implementación de soluciones.</p>
<p>Finalmente se obtuvo una calificación con un nivel de 4, en donde la comunidad le otorgó la categoría de resiliencia al componente dirigido a la cohesión social y prevención de conflictos, dado a que en la Comuna 10 siempre ha existido una organización social y comunitaria, fortalecida y participativa lo que en el 2011 les permitió hacerle frente al desastre.</p>
<div id="fig-resultados-2011" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-resultados-2011-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/capitulo4/radar-resiliencia-2011.png" class="img-fluid figure-img" width="600">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-resultados-2011-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6: Resultado de la evaluación de resiliencia comunitaria ante desastres del año 2011 (Gráfico radar de 30 componentes).
</figcaption>
</figure>
</div>
</section>
<section id="evaluación-de-resiliencia-comunitaria---año-2021" class="level3">
<h3 class="anchored" data-anchor-id="evaluación-de-resiliencia-comunitaria---año-2021">3.1.2 Evaluación de resiliencia comunitaria - Año 2021</h3>
<p>Para el año 2021 la comunidad calificó los componentes de acuerdo con la experiencia vivida, y a los aprendizajes que han surgido después del desastre durante esta década. La calificación más baja con un nivel de 1, categoría de mínima resiliencia, lo otorgaron al componente de planificación territorial y infraestructura en emergencias.</p>
<p>La comunidad otorgó un nivel de 2 en la categoría de baja resiliencia a cinco componentes para el año 2021, enfocados en la planificación del desarrollo, prácticas de medios de vida resistente a amenazas, protección de ingresos y activos y acceso a servicios financieros.</p>
<p>La comunidad otorgó a nueve componentes de la evaluación, un nivel de 3, que corresponde a la categoría de mediana resiliencia. Lo anterior permite contrastar mejoras en temas como la educación en gestión del riesgo y evaluación científica del riesgo, participación de grupos vulnerables, gestión ambiental, infraestructura crítica y vivienda.</p>
<p>La comunidad le otorgó a trece componentes de la evaluación, un nivel de 4, considerándolos en la categoría de resilientes. Esta calificación fue dirigida a componentes como evaluación comunitaria participativa del riesgo, diseminación de información, toma de decisiones comunitaria, conocimiento de derechos e incidencia, alianzas para la reducción del riesgo, acceso a servicios básicos, planificación de contingencia, sistema de alerta temprana, y capacidad de preparación respuesta y recuperación.</p>
<p>Finalmente, la comunidad otorgó un valor de 5, de alta resiliencia, a la participación de la mujer en la gestión del riesgo de desastres, ya que en el año 2021 el porcentaje de mujeres que participan en la toma de decisiones aumentó significativamente.</p>
<div id="fig-resultados-2021" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-resultados-2021-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/capitulo4/radar-resiliencia-2021.png" class="img-fluid figure-img" width="600">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-resultados-2021-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;7: Resultado de la evaluación de resiliencia comunitaria ante desastres del año 2021 (Gráfico radar de 30 componentes).
</figcaption>
</figure>
</div>
</section>
</section>
<section id="análisis-comparativo-multitemporal" class="level2">
<h2 class="anchored" data-anchor-id="análisis-comparativo-multitemporal">3.2 Análisis comparativo multitemporal</h2>
<p>En la <a href="#fig-analisis-comparativo" class="quarto-xref">Figura&nbsp;<span>8</span></a> se evidencian los contrastes entre las dos evaluaciones, hallando contrastes significativos en ciertos componentes. La diseminación de la información de reducción del riesgo de desastres pasó de un nivel 1 a 4, debido al proceso que ha surgido con la comunidad, sobre capacitación, formación y sensibilización en materia de reducción del riesgo de desastres.</p>
<p>Lo anterior está muy relacionado con la toma de decisiones comunitaria, esto se evidencia, del paso de 1 a 4, en dónde la comunidad ha tenido un nivel de empoderamiento en las decisiones que se tomen en su territorio.</p>
<p>El caso atípico, fue el valor dado a la reducción del riesgo de desastres en la planificación territorial, debido a que los líderes consideran que, en estos diez años, no se ha tenido un avance significativo en este componente.</p>
<p>La calificación más alta otorgada, fue la participación de las mujeres, pasando de un nivel de 2 a 5, siendo significativo su avance, ya que son las mujeres las que en la actualidad más participan en los temas de gestión de riesgo de desastres en la comuna 10 y están liderando diferentes procesos.</p>
<p>En el caso de las alianzas para la reducción del riesgo de desastres y recuperación, se tuvo un paso de 0 a 4 en la calificación, lo que muestra la mejora de las condiciones y capacidades de recuperación en la comuna.</p>
<p>Frente a la cohesión social y prevención de conflictos, se consideró que en el 2011 las condiciones de seguridad eran mejores que en la actualidad, pasando de un nivel de 4 a 2.</p>
<div id="fig-analisis-comparativo" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-analisis-comparativo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/capitulo4/analisis-comparativo-resiliencia.png" class="img-fluid figure-img" width="600">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-analisis-comparativo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;8: Análisis comparativo de la evaluación de resiliencia comunitaria años 2011 y 2021.
</figcaption>
</figure>
</div>
</section>
</section>
<section id="discusión" class="level1">
<h1>4. DISCUSIÓN</h1>
<p>El estudio permitió evaluar la resiliencia comunitaria frente a desastres de tipo tecnológico en la Comuna 10 de Dosquebradas, mediante la aplicación de la herramienta ARC-D en dos momentos temporales, 2011 y 2021. Esta comparación multitemporal permitió identificar avances y limitaciones en las capacidades comunitarias, evidenciando una transición de baja a mediana resiliencia en el periodo de análisis frente a estresores de tipo tecnológico.</p>
<p>La aplicación de la ARC-D demostró ser una herramienta de fácil comprensión para la comunidad y facilitó espacios participativos de reflexión sobre la gestión del riesgo. A diferencia de metodologías como la Evaluación de Vulnerabilidades y Capacidades (AVC) de la Cruz Roja Internacional, que busca sensibilizar y planificar actividades orientadas a reducir vulnerabilidades, la ARC-D se centra en medir componentes de resiliencia comunitaria de forma estructurada y participativa, con un enfoque en la percepción del riesgo de la comunidad respecto al riesgo tecnológico presente en su entorno, permitiendo además su uso en análisis multitemporales.</p>
<p>Los resultados de la medición de resiliencia comunitaria mostraron estabilidad en tres componentes a lo largo del tiempo: planificación territorial, protección de ingresos e infraestructura de emergencias. La permanencia del componente refleja tanto limitaciones estructurales, como la ausencia de cambios sustantivos en la planificación del uso de suelo, la persistencia de altos niveles de informalidad laboral y la falta de infraestructura comunitaria para la atención de emergencias.</p>
<p>Un hallazgo relevante fue el retroceso en el componente de cohesión social y prevención de conflictos, que evidencia un deterioro en la percepción de seguridad y en las medidas comunitarias de resolución de conflictos. La situación social refleja tensiones sociales que deben ser consideradas en las estrategias de gestión del riesgo, pues la cohesión social es un factor determinante de la resiliencia, tal como lo reconocen marcos internacionales como el Marco de Sendai.</p>
<p>En contraste, se observaron mejoras notorias en la participación de las mujeres y en la gobernanza comunitaria, alcanzando incluso niveles altos de resiliencia, este avance destaca el rol protagónico de las mujeres en los procesos comunitarios y la importancia de fortalecer su inclusión en la toma de decisiones.</p>
<p>De fondo respecto a la resiliencia comunitaria, se evidenció un cambio general en los niveles de resiliencia, pasando de baja en 2011 a mediana en 2021, lo cual muestra una evolución positiva en la capacidad de la comunidad para enfrentar riesgos tecnológicos.</p>
</section>
<section id="conclusiones" class="level1">
<h1>5. CONCLUSIONES</h1>
<p>El estudio tuvo como objetivo general evaluar la resiliencia comunitaria frente a desastres de tipo tecnológico en la Comuna 10 de Dosquebradas, mediante la aplicación de la herramienta ARC-D en dos momentos temporales, 2011 y 2021. Esta comparación multitemporal permitió identificar avances y limitaciones en las capacidades comunitarias, evidenciando una transición de baja a mediana resiliencia en el periodo de análisis frente a estresores de tipo tecnológico.</p>
<p>La evaluación multitemporal de la resiliencia comunitaria mediante la herramienta ARC-D permitió identificar tanto avances como limitaciones en la Comuna 10 de Dosquebradas. Estos resultados contribuyen al conocimiento aplicado sobre resiliencia comunitaria frente a riesgos tecnológicos, un campo aún poco explorado en Colombia, y ofrecen insumos prácticos para el diseño de políticas públicas y estrategias comunitarias.</p>
<div id="puntos-clave" class="callout callout-style-simple callout-important no-icon" style="background-color: #f8f0ddff; border-left: 4px solid #f7eed3ff;">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<h2 style="font-size: 1.5rem; margin-top: 0; margin-bottom: 0;" class="anchored" data-anchor-id="conclusiones">
Puntos Clave
</h2>
<ul>
<li>En 2011 la resiliencia comunitaria frente a riesgo tecnológico en la Comuna 10 era baja (30.08%), lo que agravó los impactos del desastre presentado en la explosión.</li>
<li>Entre 2011 y 2021 la resiliencia aumentó a un nivel medio (60.18%) gracias a los procesos de recuperación postdesastre, los aprendizajes colectivos y el mayor liderazgo de las mujeres.</li>
<li>Para la gestión del riesgo actual, persisten limitaciones en planificación territorial, protección de ingresos e infraestructura de emergencias.</li>
<li>La participación de las mujeres emergió como el componente con mayor progreso, pasando de nivel 2 a 5.</li>
</ul>
</div>
</div>
</div>
<div id="preguntas" class="callout callout-style-simple callout-important no-icon" style="background-color: #f3eaf8ff; border-left: 4px solid #efe3f7ff;">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<h2 style="font-size: 1.5rem; margin-top: 0; margin-bottom: 0;" class="anchored">
Preguntas por resolver
</h2>
<ul>
<li>¿Cómo fortalecer los componentes que permanecen en baja resiliencia, como la planificación territorial integrada con gestión del riesgo?</li>
<li>¿Cuál es la causa del deterioro en cohesión social y prevención de conflictos en el período 2011-2021, y cómo revertirlo?</li>
<li>¿De qué manera los municipios pueden integrar explícitamente el riesgo tecnológico en sus instrumentos de planificación?</li>
<li>¿Cuáles son los mecanismos para sostener las mejoras alcanzadas y evitar retrocesos en resiliencia?</li>
</ul>
</div>
</div>
</div>
<div id="recomendaciones" class="callout callout-style-simple callout-important no-icon" style="background-color: #f8dedcff; border-left: 4px solid #fad4d1ff;">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<h2 style="font-size: 1.5rem; margin-top: 0; margin-bottom: 0;" class="anchored">
Recomendaciones para tomar decisiones
</h2>
<ul>
<li>Replicar la aplicación de la herramienta ARC-D en otros municipios para evaluar y fortalecer la resiliencia comunitaria frente a riesgos tecnológicos.</li>
<li>Incluir el riesgo tecnológico de forma explícita en los planes de gestión del riesgo y en los instrumentos de planificación territorial a nivel municipal.</li>
<li>Socializar y sensibilizar a la comunidad sobre el riesgo tecnológico, vinculándolo a la vida cotidiana, los medios de vida y la movilidad.</li>
<li>Usar la ARC-D como insumo para diagnósticos locales en el marco de la iniciativa MCR2030, articulando sus resultados con los planes municipales.</li>
<li>En el caso de Dosquebradas, expandir el ejercicio a otros escenarios de riesgo para aprovechar aprendizajes y fortalecer la preparación comunitaria.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="conflicto-de-intereses" class="level1">
<h1>CONFLICTO DE INTERESES</h1>
<p>Los autores no declaran conflicto de intereses.</p>
</section>
<section id="uso-de-herramientas-de-inteligencia-artificial" class="level1">
<h1>USO DE HERRAMIENTAS DE INTELIGENCIA ARTIFICIAL</h1>
<p>Durante la preparación de este capítulo, los autores utilizaron ChatGPT versión GPT-4o (https://chatgpt.com) con el fin de recibir sugerencias de redacción y corrección del estilo científico. Los revisores expresan que no utilizaron herramientas de IA en el proceso de evaluación del manuscrito.</p>
</section>
<section id="agradecimientos" class="level1">
<h1>AGRADECIMIENTOS</h1>
<p>Queremos agradecer a los líderes de la Comuna 10 del municipio de Dosquebradas, por su apoyo y participación en las reuniones previas y grupo focal, lo cual fue de vital importancia para la obtención de los resultados. Especialmente, queremos agradecer a Don Elmer Castañeda y Diego Buitrago, líderes y expertos comunitarios en la gestión del riesgo de desastres en la Comuna 10, los cuales apoyaron de manera desinteresada esta evaluación de resiliencia comunitaria, viéndola como una oportunidad para el proceso de la gestión de riesgo.</p>
</section>
<section id="identificación-de-autores" class="level1">
<h1>IDENTIFICACIÓN DE AUTORES</h1>
<p><strong>Evelin Langebeck Cuéllar</strong></p>
<p>https://scholar.google.es/citations?user=FzyY5g8AAAAJ&amp;hl=es</p>
<p><strong>Nicolás Giraldo Hernández</strong></p>
<p>https://scienti.minciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0001984270</p>
</section>
<section id="declaración-de-autoría-credit" class="level1">
<h1>DECLARACIÓN DE AUTORÍA CRediT</h1>
<p>Todos los autores contribuyeron a la conceptualización y desarrollo de este proyecto. Evelin Langebeck Cuéllar lideró la metodología y la recolección de datos comunitarios. Nicolás Giraldo Hernández coordinó el análisis de datos y la interpretación de resultados. Ambos autores revisaron críticamente y aprobaron la versión final del manuscrito.</p>
</section>
<section id="bibliografía" class="level1">
<h1>BIBLIOGRAFÍA</h1>
<div id="refs" class="references csl-bib-body" role="list" style="display: none">
<div id="ref-cruzroja2006" class="csl-entry" role="listitem">
<div class="csl-left-margin">1. </div><div class="csl-right-inline">Cruz Roja Internacional. ¿Cómo se hace un AVC? Guía práctica para el personal y los voluntarios de la Cruz Roja y de la Media Luna Roja. Cruz Roja; 2006. </div>
</div>
<div id="ref-onu2016" class="csl-entry" role="listitem">
<div class="csl-left-margin">2. </div><div class="csl-right-inline">ONU (Oficina de las Naciones Unidas para la Reducción del Riesgo de Desastres). Informe del grupo de trabajo intergubernamental de expertos de composición abierta sobre los indicadores y la terminología relacionados con la reducción del riesgo de desastres. Naciones Unidas; 2016. </div>
</div>
<div id="ref-ciccotti2020" class="csl-entry" role="listitem">
<div class="csl-left-margin">3. </div><div class="csl-right-inline">Ciccotti L, Rodrigues A, Boscov M, Gunther W. <a href="https://doi.org/10.1590/1809-4422asoc20190151vu2020L3AO">Building indicators of community resilience to disasters in Brazil: A participatory approach</a>. Ambiente &amp; Sociedade. 2020;23:1-24. </div>
</div>
<div id="ref-unisdr2009" class="csl-entry" role="listitem">
<div class="csl-left-margin">4. </div><div class="csl-right-inline">ONU (Oficina de las Naciones Unidas para la Reducción del Riesgo de Desastres). Terminología sobre reducción del riesgo de desastres [Internet]. UNISDR; 2009. Disponible en: <a href="https://www.unisdr.org/files/7817_UNISDRTerminologySpanish.pdf">https://www.unisdr.org/files/7817_UNISDRTerminologySpanish.pdf</a></div>
</div>
<div id="ref-mccaul2016" class="csl-entry" role="listitem">
<div class="csl-left-margin">5. </div><div class="csl-right-inline">McCaul B, Mitsidou A. Análisis de la resiliencia de las comunidades ante desastres. GOAL; 2016. </div>
</div>
<div id="ref-sandoval2022" class="csl-entry" role="listitem">
<div class="csl-left-margin">6. </div><div class="csl-right-inline">Sandoval V, Navarrete F, Cuadra S. Resiliencia comunitaria ante desastres en América Latina: tendencias y desafíos. Revista de Estudios Latinoamericanos sobre Reducción del Riesgo de Desastres. 2022;6(1):45-67. </div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Capitulo3.html" class="pagination-link" aria-label="3. Gestión del Riesgo de Desastres Comunitario a través de Cartografía Participativa y Tecnologías Abiertas en San José del Prado, Colombia">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">3. Gestión del Riesgo de Desastres Comunitario a través de Cartografía Participativa y Tecnologías Abiertas en San José del Prado, Colombia</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Capitulo5.html" class="pagination-link" aria-label="5. Avances y desafíos del manejo de desastres y gestión del riesgo volcánico con animales de producción">
        <span class="nav-page-text"><span class="chapter-title">5. Avances y desafíos del manejo de desastres y gestión del riesgo volcánico con animales de producción</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>