name: Build and Deploy Quarto Site

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install OJS dependencies
        run: |
          npm install -g d3
          npm install -g @observablehq/runtime

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Check Quarto version
        run: quarto --version

      - name: List files
        run: ls -la

      - name: Render Quarto Project
        run: |
          echo "Starting Quarto render..."
          quarto render --to html --verbose 2>&1 | tee render_output.log
          echo "Render completed with exit code: $?"
          if [ ! -d "_book" ]; then
            echo "ERROR: _book directory was not created!"
            exit 1
          fi
          echo "Contents of _book:"
          ls -la _book/
        continue-on-error: false
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_book

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4